# Launched with `hemtt launch`
[default]
workshop = [
    "450814997",  # CBA_A3's Workshop ID
    "894678801",  # TFAR Beta
    "1779063631", # Zeus Enhanced 
    "3499977893", # Advanced Developer Tools
    "463939057",  # ACE
    #"1645973522", # Intercept Minimal Dev
    #"1585582292", # Arma Debug Engine
]

parameters = []
dlc = []
optionals = []

[WS]
extends = "default"
dlc = ["ws"]
mission = "WS.SefrouRamal"

[SPE]
extends = "default"
dlc = ["spe"]
mission = "SPE.SPE_Mortain"

[BOTH]
extends = "WS"
dlc = ["spe"]